### ISSUE TITLE
Pre fetch data

### ISSUE THREAD

**Issue by d6u** [guidsen/react-simple-universal#1]
Thanks for creating this project. React did a good job on enabling server rendering.

But the mean problem I think is how to prefetch data, the reset are solved already (we just need to improve the API). As we all know `renderToString` is sync, there is no opportunity for a component to ask for data it wants. All data have to be known before `renderToString`, and we have to "push" the data the the template (React components) like we always do on server side. But that's not optimal for two reason:
1. We are defining the same logic in two different places. If a component has logic on what data it needs, we are ignoring it on server, means we have to define them again somewhere on server.
2. There are essentially different ways to get data on client and server. On client, we make AJAX requests (or whatever) but on server we can just provide data in the sam runtime (well I know with something like [axios](https://github.com/mzabriskie/axios) you can make HTTP request on server, but really? We can already access the data in memory, why incur extra overhead).

I've tried [react-fetcher](https://github.com/markdalgleish/react-fetcher), [react-resolver](https://github.com/ericclemmons/react-resolver). None of those seems to solve those problems. [react-transmit](https://github.com/RickWong/react-transmit) is the closest one. But lots of boilerplate, and also still not providing any elegant universal solutions both on server and on client.

So do you have any suggestions on the best way to do that?

**Comment by guidsen** [comment]
Indeed React did a great job on enabling server rendering. At the moment there is just to much boilerplate involved to create universal React apps and I think this is an issue for most of the developers.  
I've been thinking about pre fetching data as well. First I was thinking about decorating these actions, like the libs you mentioned (`react-fetcher` and `react-resolver`). But this didn't look really elegant to me.

**What I came up with:**
I'm not sure if this approach works, but I've been brainstorming about it a while ago.
Since we are using Redux, maybe we can leverage the initial data on each reducer. When using `react-simple-universal/server` we might implement logic to somehow pass the data that we retrieve from our actions to our state. This way we can populate our state with server side data and have the actions defined in one place. Also we can avoid having much boilerplate like a decorator on each component, which is just a **no** imho. I could've missed something here, but that's what might be an option.

I would love to know what you came up with!

**Comment by d6u** [comment]
@guidsen https://github.com/d6u/github-starboard/blob/master/source/server/routers/util/renderReact.js#L16-L27 is basically what you suggested here. I think redux works very well this way. And if this is good enough, our conversation can end here.

But (as you may have already know :smile:), I don't think Redux is good enough. I like the declarative style from Relay better (Relay team seems to marching on the direction https://github.com/facebook/relay/issues/136). But before Relay server rendering is a thing, I don't think everybody will use GraphQL. I found [Falcor](https://github.com/Netflix/falcor) to be more acceptable. But unlike Relay, Falcor (Falcor can run on server apparently) doesn't have first class server rendering support like Relay does. So really we are nowhere close to a realistic declarative universal rendering solution, unless we can somehow make `renderToString` async.

Anyway, if you are not interested, you can ignore the second paragraph.

**Comment by guidsen** [comment]
Not really worked with Relay yet, and I'm not sure if people will use GraphQL yet. I've been looking into Falcor as well and it seems pretty cool. We might built a little experiment on top of it and see if we can somehow combine this with the Redux store. But I think we should focus on a way to let `renderToString` behave async. 

Maybe we should take a step back and see if we can come up with a declarative API on top of Express?

**Comment by d6u** [comment]
Definitely. Do you think there is anything I or someone else can help?

**Comment by guidsen** [comment]
This just came up in my mind: could we build a decorated component on top of the React Router `Route` component?

Something like:

``` javascript
import fetchMembers from 'actions/fetchMembers';
import fetchMemberDetails from 'actions/fetchMemberDetails';

<Route path="/members" component={MyComponent} onReset={fetchMembers} />;

// The only problem here is the fact we need to map the id route param to the action.
<Route path="/members/:id" component={MyComponent} onReset={fetchMemberDetails} />;
```

What do you think about this? Better than having a decorator on top of each component, because fetching the data should be on the routing level imho.
We should make the universal think easy to step into. Things like Falcor and Relay will probably discourage developers to try it out.

**Comment by d6u** [comment]
The router loading data is a fine pattern. Many frameworks embrace it. E.g. in Ember, you can return a promise within a router, so the view will wait for the promise to resolve (into, most likely, some data). I think this is what [`onEnter`](https://github.com/rackt/react-router/blob/latest/docs/API.md#onenternextstate-replacestate-callback) will do.

Do you mean `onReset` should be an API just for server or both server and client? Because I think `onEnter` is just for client, it won't be invoked on server.

**Comment by guidsen** [comment]
The `onEnter` will only fire once the client is loaded (im not 100% sure). So the `onReset` should only be an API hook just for the server to fire. We can fire the `onReset` inside the logic where we render the routes on the server. I can create a new issue with some options where the people can vote on.

**Comment by d6u** [comment]
I see. How do you write the source code with this API? If we reused the same file, we will also see `onReset={fetchMembers}` on client code. Thus `actions/fetchMembers` will be imported while build. Do you think we need something like [null-loader](https://github.com/webpack/null-loader) to nullify `actions/fetchMembers` when bundle client side code? I don't think this is a elegant API since we shouldn't force users to commit to any bundler.

**Comment by guidsen** [comment]
Hmmm yes we dont want the `onReset` to be used on the client and we shouldn't introduce more dependencies. Is there any way we can decorate the `Route` component so we will be able to add the `onReset` only on the server? If not, we should look for another option to simplify this. I think we are heading in the right direction though.

**Comment by d6u** [comment]
I think a better API would be generate an express router middleware based on react-router's routes.

``` js
import routes from './routes';

var app = express();
var router = getExpressRouter(routes); // router should an instance of express.Router

app.use(router);
```

Edited:

I think the real challenge of this approach is how to handle custom routing rules, e.g. authentication or redirections based on server only elements like sessions or cookies.

Edited 2:

I asked this question on Twitter once https://twitter.com/ryanflorence/status/689884907066101760, but no solution found.

**Comment by guidsen** [comment]
So generating a Router based on the React routes looks good to me. But indeed the real challenge is handling custom routing rules. Maybe we could do something with the `match()` function in React-Router.  Couldn't we redirect if we send the URL to be redirected to the `match()` function? I can experiment a bit on this tonight to check out the possibilities.

**Comment by d6u** [comment]
> redirect if we send the URL to be redirected to the match() function

Can you give an example? Are you saying passing additional option to `match()`?

**Comment by guidsen** [comment]
Was a quick brainstorm session yesterday. 

Well when we want to redirect to another URL, we might trigger the `match()` function again on redirection since there the markup from the router will be rendered, right?

**Comment by d6u** [comment]
You mean something like this?

``` js
app.get('/dashboard', function (res, req) {
  req.redirect('/'); // not authed, go away
});

app.get('/', function (res, req) {
  match(res.url, ..., function () {
    // do things here, maybe we will go to /login, maybe not
  });
});
```

**Comment by guidsen** [comment]
Yes, that looks good. Do you think this will work? Are we missing something here? Anyone around here has other suggestions? 

Maybe to avoid having a `match()` in your express routes, we might handle this inside a kinda "before" middleware where we can trigger the `match()` on every incoming request and pass it to the route handler. I'm not sure if this is even possible in Express. This will avoid having the `match(res.url, ....)` part in every route to pre fetch data for that route.

**Comment by d6u** [comment]
I think `match()` both "before" and "after" express middleware should work theoretically. But I think putting `match()` "after" express routing makes better sense. Because `match()` will provide more than just routing, it will also provide the [`renderProps`](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md#server-rendering) to render the React components. If you put `match()` before express routing logic, you will have to carry `renderProps` around for all later middlewares. I think it make more sense to just render React immediately after we got the `renderProps`.

When I say "'before' and 'after' express middleware", I really just say add an extra middleware that dedicated to handle `match()`. I don't think handling server routing outside of a middleware makes sense.

**Comment by guidsen** [comment]
I agree. Theoretically this would be a huge move into pre fetching data as well, right? Or are we missing something? Having this `match()` solution acting like a "after" middleware to trigger redirects etc and the express routing on page reset. How would we pre fetch the data? With the Express routes?

**Comment by d6u** [comment]
Didn't quite understand, are you proposing:

```
GET any -> express router logic -> match() -> fetching data -> render -> HTML response
```

or 

```
GET any -> match() -> express router logic -> fetching data -> render -> HTML response
```

**Comment by guidsen** [comment]
The first one ;). Like you said having the `match()` after the express route so we can use the `renderProps` if needed.

**Comment by d6u** [comment]
If we order the routing like this:

```
GET any -> express router logic -> match() -> fetching data -> render -> HTML response
```

I think we went back to the original question -- what's the best way to prefetch data. I cannot think of a good solution right now.

**Comment by guidsen** [comment]
Well maybe we can start implementing to build a better API for creating universal apps and create express routes based on the React routes. That's a good improvement for the way we currently create universal apps. We might implement a way to prefetch data later. Maybe if this repo is getting more popular there are other people that have good suggestions. 

Tonight and tomorrow I got time to start setting up some boilerplate.

**Comment by d6u** [comment]
Cool! Keep me posted.
