### ISSUE TITLE
Roughly 90% complete

### ISSUE THREAD

**Issue by ghost** [guidsen/react-simple-universal#2]
I like that all these repos are popping up describing the same problem to be solved.  I've been working on solving this exact problem (among a couple of others) for the past couple of months or so.  I'm creating an issue here as a bit of a reminder for myself to link here when I'm finished.  There will be a detailed writeup about everything as well.  :+1:

**Comment by guidsen** [comment]
Cool, keep me updated. Open this issue when you are done ;)!

**Comment by ghost** [comment]
https://medium.com/@timbur/react-automatic-redux-providers-and-replicators-c4e35a39f1
